// <auto-generated />
using System;
using KansaiExplore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KansaiExplore.Migrations.Data
{
    [DbContext(typeof(DataContext))]
    [Migration("20250223043233_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KansaiExplore.Data.Shared.NicheSpot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Choordinates")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("choordinates");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("media_url");

                    b.Property<string>("SpotDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("spot_description");

                    b.Property<string>("SpotName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("spot_name");

                    b.HasKey("Id");

                    b.ToTable("kansaispot");

                    b.HasData(
                        new
                        {
                            Id = new Guid("70b41be5-9914-4bc8-871a-c9724121e5bc"),
                            Choordinates = "13333,1111",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 2, 23, 13, 32, 32, 719, DateTimeKind.Unspecified).AddTicks(4849), new TimeSpan(0, 9, 0, 0, 0)),
                            CreatedBy = new Guid("bcff8153-539f-46c8-83a1-f0094c126c96"),
                            Latitude = 0.0,
                            Longitude = 0.0,
                            MediaUrl = "example.com",
                            SpotDescription = "てすとだよ",
                            SpotName = "Test"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
