// <auto-generated />
using System;
using KansaiExplore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KansaiExplore.Migrations.Data
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KansaiExplore.Data.Shared.NicheSpot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Choordinates")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("choordinates");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric")
                        .HasColumnName("longitude");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("media_url");

                    b.Property<string>("SpotDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("spot_description");

                    b.Property<string>("SpotName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("spot_name");

                    b.HasKey("Id");

                    b.ToTable("kansaispot");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cf24d8e7-48cf-42a8-9828-0ed5eea8ab03"),
                            Choordinates = "13333,1111",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 2, 23, 13, 0, 24, 391, DateTimeKind.Unspecified).AddTicks(3534), new TimeSpan(0, 9, 0, 0, 0)),
                            CreatedBy = new Guid("f93f84f8-c150-437f-b62a-c015ca92a41c"),
                            Latitude = 0m,
                            Longitude = 0m,
                            MediaUrl = "example.com",
                            SpotDescription = "てすとだよ",
                            SpotName = "Test"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
